let obj ={
    data:[{
        name:'首页',
        key:'0',
        path:'/admin/home'
    },
    {
        name:'商品管理',
        key:'1',
        path:'/admin/food',
        children:[
            {
                name:'商品列表',
                key:'1-0',
                path:'/admin/food/list',
            },
            {
                name:'商品添加',
                key:'1-1',
                path:'/admin/food/add',
            },
        ]
      },
      {
        name:'营销',
        key:'2',
        path:'/admin/market',
        children:[
            {
                name:'广告列表',
                key:'2-0',
                path:'/admin/market/banner',
            },
        ]
      },
      {
        name:'订单管理',
        key:'3',
        path:'/admin/order',
        children:[
            {
                name:'订单列表',
                key:'3-0',
                path:'/admin/order/list',
            },
            {
                name:'退货申请',
                key:'3-1',
                path:'/admin/order/things',
            },
        ]
      },
    ]
}
export default obj